// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPlJz-KSLjChE97WnGcKQsY4s5fYts4EY',
    appId: '1:88079836718:web:42a4b0409583609431e1bf',
    messagingSenderId: '88079836718',
    projectId: 'tapastop-80374',
    authDomain: 'tapastop-80374.firebaseapp.com',
    storageBucket: 'tapastop-80374.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcj7-0JewwdE8choh7SDiVBfADrnvPy3I',
    appId: '1:88079836718:android:81be85f64c8b7d6e31e1bf',
    messagingSenderId: '88079836718',
    projectId: 'tapastop-80374',
    storageBucket: 'tapastop-80374.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw9wxoF52YAg818TEg1UFW7_TnekTF5CQ',
    appId: '1:88079836718:ios:82afc9b393a43d7f31e1bf',
    messagingSenderId: '88079836718',
    projectId: 'tapastop-80374',
    storageBucket: 'tapastop-80374.appspot.com',
    iosClientId:
        '88079836718-is75hvp9is8v76uk9ljre0bhv3ijivi3.apps.googleusercontent.com',
    iosBundleId: 'com.upm.isii.grupo62.tapastop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw9wxoF52YAg818TEg1UFW7_TnekTF5CQ',
    appId: '1:88079836718:ios:82afc9b393a43d7f31e1bf',
    messagingSenderId: '88079836718',
    projectId: 'tapastop-80374',
    storageBucket: 'tapastop-80374.appspot.com',
    iosClientId:
        '88079836718-is75hvp9is8v76uk9ljre0bhv3ijivi3.apps.googleusercontent.com',
    iosBundleId: 'com.upm.isii.grupo62.tapastop',
  );
}
